### ISSUE TITLE
Can't build, definitions.owl not found

### ISSUE THREAD

**Issue by srobb1** [INCATools/ontology-development-kit#103]
Hi All,
I have my new phenotype ontology and I am trying to `./build.sh -vvv` but am getting some errors. 

```
Caused by: java.io.FileNotFoundException: /Users/smr/src/ontology-development-kit/target/planarian-phenotype-ontology/src/patterns/definitions.owl (No such file or directory)
```

but it does exisit

```
mp02gtfh05:ontology smr$ ls -l  /Users/smr/src/ontology-development-kit/target/planarian-phenotype-ontology/src/patterns/definitions.owl
-rw-r--r--  1 smr  SGC\Domain Users  886916 Sep  7 14:25 /Users/smr/src/ontology-development-kit/target/planarian-phenotype-ontology/src/patterns/definitions.owl
```

Not sure what to try.

Thank you,
Sofia

Here is the full output when I run the build:
```
mp02gtfh05:ontology smr$  ./build.sh -vvv
mkdir -p target/intermediates/patterns &&\
dosdp-tools generate --catalog=catalog-v001.xml --infile=../patterns/abnormal.tsv --template=../patterns/abnormal.yaml --ontology=planp-edit.owl --obo-prefixes=true  --outfile=target/intermediates/patterns/abnormal.ofn
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Could not load imported ontology: <http://purl.obolibrary.org/obo/planp/patterns/defintions.owl> Cause: /Users/smr/src/ontology-development-kit/target/planarian-phenotype-ontology/src/patterns/definitions.owl (No such file or directory)
Exception in thread "main" org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/planp/patterns/defintions.owl> Cause: /Users/smr/src/ontology-development-kit/target/planarian-phenotype-ontology/src/patterns/definitions.owl (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1866)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1537)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:194)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1545)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:370)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:236)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:658)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:201)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:145)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1250)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1204)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1104)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1060)
	at org.monarchinitiative.dosdp.cli.Common.$anonfun$ontologyOpt$1(Common.scala:42)
	at scala.Option.map(Option.scala:146)
	at org.monarchinitiative.dosdp.cli.Common.ontologyOpt(Common.scala:38)
	at org.monarchinitiative.dosdp.cli.Common.ontologyOpt$(Common.scala:38)
	at org.monarchinitiative.dosdp.cli.Generate$.ontologyOpt(Generate.scala:24)
	at org.monarchinitiative.dosdp.cli.Generate$.run(Generate.scala:41)
	at org.monarchinitiative.dosdp.cli.Main$.$anonfun$new$1(Main.scala:33)
	at org.monarchinitiative.dosdp.cli.Main$.$anonfun$new$1$adapted(Main.scala:33)
	at scala.Option.foreach(Option.scala:257)
	at org.monarchinitiative.dosdp.cli.Main$.delayedEndpoint$org$monarchinitiative$dosdp$cli$Main$1(Main.scala:33)
	at org.monarchinitiative.dosdp.cli.Main$delayedInit$body.apply(Main.scala:29)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.monarchinitiative.dosdp.cli.Main$.main(Main.scala:29)
	at org.monarchinitiative.dosdp.cli.Main.main(Main.scala)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: /Users/smr/src/ontology-development-kit/target/planarian-phenotype-ontology/src/patterns/definitions.owl (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:230)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1250)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1204)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1104)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1821)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1859)
	... 47 more
Caused by: java.io.FileNotFoundException: /Users/smr/src/ontology-development-kit/target/planarian-phenotype-ontology/src/patterns/definitions.owl (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:178)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:140)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:263)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	... 52 more
Makefile:173: recipe for target 'target/intermediates/patterns/abnormal.ofn' failed
make: *** [target/intermediates/patterns/abnormal.ofn] Error 1

```

**Comment by matentzn** [comment]
I have a feeling what that must have been. Did you use the latest version from a 4 hours ago?

**Comment by matentzn** [comment]
@cmungall I think this should fix it
https://github.com/INCATools/ontology-development-kit/pull/102

Can you review?

**Comment by srobb1** [comment]
@matentzn My first try no, a version from a couple weeks ago. But then I pulled the new changes from 20min ago, and have the same message.

**Comment by srobb1** [comment]
@matentzn  I just made the change that you propose #102 but I get the same messages.

**Comment by matentzn** [comment]
Can you print the contents of catalog-v001.xml in the ontology directory?

**Comment by srobb1** [comment]
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <uri id="Imports Wizard Entry" name="http://purl.obolibrary.org/obo/plana/releases/2018-07-24/plana.owl" uri="imports/plana_import.owl"/>
    <uri id="Imports Wizard Entry" name="http://purl.obolibrary.org/obo/pato/releases/2018-08-14/pato.owl" uri="imports/pato_import.owl"/>
    <uri id="Imports Wizard Entry" name="http://purl.obolibrary.org/obo/planp/patterns/defintions.owl" uri="file:/Users/smr/src/ontology-development-kit/target/planarian-phenotype-ontology/src/patterns/definitions.owl"/>
    <group id="Folder Repository, directory=, recursive=true, Auto-Update=true, version=2" prefer="public" xml:base="">
        <uri id="Automatically generated entry, Timestamp=1536351843251" name="http://purl.obolibrary.org/obo" uri="imports/plana_import.owl"/>
        <uri id="Automatically generated entry, Timestamp=1536351843251" name="http://purl.obolibrary.org/obo/pato.owl" uri="imports/pato_import.owl"/>
        <uri id="Automatically generated entry, Timestamp=1536351843251" name="duplicate:http://purl.obolibrary.org/obo/planp.owl" uri="ed_definitions_merged.owl"/>
        <uri id="Automatically generated entry, Timestamp=1536351843251" name="duplicate:http://purl.obolibrary.org/obo/planp.owl" uri="planp.owl"/>
        <uri id="Automatically generated entry, Timestamp=1536351843251" name="http://purl.obolibrary.org/obo/planp.owl/" uri="planp-edit.owl"/>
        <uri id="Automatically generated entry, Timestamp=1536351843251" name="http://purl.obolibrary.org/obo/planp/imports/ro_import.owl" uri="imports/ro_import.owl"/>
        <uri id="Automatically generated entry, Timestamp=1536351843251" name="http://purl.obolibrary.org/obo/ro.owl" uri="mirror/ro.owl"/>
    </group>
</catalog>
```

**Comment by matentzn** [comment]
Hm strange.. Mine looks more like this when I generate a new ontology using the ODK:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <uri id="User Entered Import Resolution" name="http://purl.obolibrary.org/obo/abo4/imports/po_import.owl" uri="imports/po_import.owl"/>
  <uri id="User Entered Import Resolution" name="http://purl.obolibrary.org/obo/abo4/imports/ro_import.owl" uri="imports/ro_import.owl"/>
  <uri id="User Entered Import Resolution" name="http://purl.obolibrary.org/obo/abo4/imports/pato_import.owl" uri="imports/pato_import.owl"/>
  <uri id="User Entered Import Resolution" name="http://purl.obolibrary.org/obo/abo4/patterns/definitions.owl" uri="../patterns/definitions.owl"/>
    <group id="Folder Repository, directory=, recursive=false, Auto-Update=false, version=2" prefer="public" xml:base=""/>
</catalog>
```

I think we have to wait for @dosumis and @cmungall to advice. Sorry!

**Comment by srobb1** [comment]
It isn't brand new. I have done some work in protege with it.

**Comment by srobb1** [comment]
I used your catalog file and
1.  replaced abo4 with my prefix
2. replaced po_import with plana_import

It is working. It is an issue with full paths versus relative paths.

But I have some other problems now, but I am not sure what exactly is wrong. 

Here is the output when I build:
```
mp02gtfh05:ontology smr$ ./build.sh
robot convert -I http://purl.obolibrary.org/obo/ro.owl -o mirror/ro.owl
mkdir -p target/intermediates/patterns &&\
dosdp-tools generate --catalog=catalog-v001.xml --infile=../patterns/abnormal.tsv --template=../patterns/abnormal.yaml --ontology=planp-edit.owl --obo-prefixes=true  --outfile=target/intermediates/patterns/abnormal.ofn
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
robot merge -i target/intermediates/patterns/abnormal.ofn annotate --ontology-iri http://purl.obolibrary.org/obo/planp/patterns/defintions.owl -o ../patterns/definitions.owl
robot merge -i planp-edit.owl -i ../patterns/definitions.owl -o ed_definitions_merged.owl
robot query -f csv -i ed_definitions_merged.owl --query ../sparql/terms.sparql seed.txt
cat seed.txt imports/ro_terms.txt | sort | uniq >  imports/ro_terms_combined.txt
robot extract -i mirror/ro.owl -T imports/ro_terms_combined.txt --method BOT -O http://purl.obolibrary.org/obo/planp/imports/ro_import.owl -o imports/ro_import.owl
robot convert --check false -i imports/ro_import.owl -f obo -o imports/ro_import.obo.tmp && mv imports/ro_import.obo.tmp imports/ro_import.obo
2018-09-08 03:54:35,318 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : DisjointClasses(<http://purl.obolibrary.org/obo/BFO_0000002> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/BFO_0000003>))»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:1429)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:261)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:549)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
2018-09-08 03:54:35,337 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : SubObjectPropertyOf(<http://purl.obolibrary.org/obo/RO_0002333> InverseOf(<http://purl.obolibrary.org/obo/RO_0002215>))»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:743)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:271)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:549)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
2018-09-08 03:54:35,376 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : DisjointClasses(<http://purl.obolibrary.org/obo/BFO_0000003> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/BFO_0000002>))»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:1429)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:261)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:549)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
2018-09-08 03:54:35,389 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : SubClassOf(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002566> <http://purl.obolibrary.org/obo/BFO_0000040>) ObjectUnionOf(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000056> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002418> <http://purl.obolibrary.org/obo/BFO_0000015>)) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000056> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002418> <http://purl.obolibrary.org/obo/BFO_0000015>)))))»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:2101)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:259)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:549)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
robot verify  --catalog catalog-v001.xml -i planp-edit.owl --queries ../sparql/equivalent-classes-violation.sparql ../sparql/trailing-whitespace-violation.sparql ../sparql/owldef-self-reference-violation.sparql ../sparql/xref-syntax-violation.sparql ../sparql/nolabels-violation.sparql -O reports/
PASS Rule ../sparql/equivalent-classes-violation.sparql: 0 violation(s)
PASS Rule ../sparql/trailing-whitespace-violation.sparql: 0 violation(s)
PASS Rule ../sparql/owldef-self-reference-violation.sparql: 0 violation(s)
PASS Rule ../sparql/xref-syntax-violation.sparql: 0 violation(s)
PASS Rule ../sparql/nolabels-violation.sparql: 0 violation(s)
simple_pattern_tester.py ../patterns/ # 2>&1 | tee pattern_schema_checks
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/abnormal.yaml
  warnings.warn("Checking %s" % pattern_doc)
dosdp-tools prototype --obo-prefixes --template=../patterns --outfile=../patterns/pattern.owl
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
robot query -f csv -i ../patterns/pattern.owl --query ../sparql/terms.sparql ../patterns/imports/seed.txt
cat ../patterns/imports/seed.txt | sort | uniq > ../patterns/imports/seed_sorted.txt
robot extract -i mirror/ro.owl -T ../patterns/imports/seed_sorted.txt --method BOT -O mirror/ro.owl annotate --ontology-iri http://purl.obolibrary.org/obo/planp/patterns/imports/ro_import.owl -o ../patterns/imports/ro_import.owl
2018-09-08 03:55:04,687 ERROR org.semanticweb.owlapi.model.OWLOntologyID - Ontology IRIs must be absolute; IRI mirror/ro.owl is relative and will be made absolute by prefixing urn:absolute: to it
cat patterns.sh >patterns
chmod a+x patterns
robot  reason -i planp-edit.owl -r ELK relax reduce -r ELK annotate -V http://purl.obolibrary.org/obo/planp/releases/`date +%Y-%m-%d`/planp.owl -o planp.owl
2018-09-08 03:55:15,923 ERROR org.obolibrary.robot.ReasonOperation - Reference violations found: 1302 - reasoning may be incomplete
2018-09-08 03:55:15,926 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000241>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000241>, category=DANGLING]
2018-09-08 03:55:15,927 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubObjectPropertyOf(<http://purl.obolibrary.org/obo/RO_0002584> <http://purl.obolibrary.org/obo/RO_0002328>), referencedObject=<http://purl.obolibrary.org/obo/RO_0002328>, category=DANGLING]
2018-09-08 03:55:15,927 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000184>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000184>, category=DANGLING]
2018-09-08 03:55:15,928 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000525>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000525>, category=DANGLING]
2018-09-08 03:55:15,928 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000155>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000155>, category=DANGLING]
2018-09-08 03:55:15,928 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000597>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000597>, category=DANGLING]
2018-09-08 03:55:15,929 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000267>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000267>, category=DANGLING]
2018-09-08 03:55:15,929 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000839>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000839>, category=DANGLING]
2018-09-08 03:55:15,929 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000750>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000750>, category=DANGLING]
2018-09-08 03:55:15,930 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000900>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000900>, category=DANGLING]
robot convert -i planp.owl -f obo -o planp.obo.tmp && mv planp.obo.tmp planp.obo
ONTOLOGY STORAGE ERROR Could not save ontology to IRI: file:/work/src/ontology/planp.obo.tmp
For details see: http://robot.obolibrary.org/errors#ontology-storage-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
Makefile:50: recipe for target 'planp.obo' failed
make: *** [planp.obo] Error 1
rm imports/ro_terms_combined.txt
mp02gtfh05:ontology smr$
```

**Comment by matentzn** [comment]
I opened another issue for your new problem
https://github.com/INCATools/ontology-development-kit/issues/104
