### ISSUE TITLE
Ontology storage exception when running build.sh

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#104]
From @srobb1, see https://github.com/INCATools/ontology-development-kit/issues/103

```
mp02gtfh05:ontology smr$ ./build.sh
robot convert -I http://purl.obolibrary.org/obo/ro.owl -o mirror/ro.owl
mkdir -p target/intermediates/patterns &&\
dosdp-tools generate --catalog=catalog-v001.xml --infile=../patterns/abnormal.tsv --template=../patterns/abnormal.yaml --ontology=planp-edit.owl --obo-prefixes=true  --outfile=target/intermediates/patterns/abnormal.ofn
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
robot merge -i target/intermediates/patterns/abnormal.ofn annotate --ontology-iri http://purl.obolibrary.org/obo/planp/patterns/defintions.owl -o ../patterns/definitions.owl
robot merge -i planp-edit.owl -i ../patterns/definitions.owl -o ed_definitions_merged.owl
robot query -f csv -i ed_definitions_merged.owl --query ../sparql/terms.sparql seed.txt
cat seed.txt imports/ro_terms.txt | sort | uniq >  imports/ro_terms_combined.txt
robot extract -i mirror/ro.owl -T imports/ro_terms_combined.txt --method BOT -O http://purl.obolibrary.org/obo/planp/imports/ro_import.owl -o imports/ro_import.owl
robot convert --check false -i imports/ro_import.owl -f obo -o imports/ro_import.obo.tmp && mv imports/ro_import.obo.tmp imports/ro_import.obo
2018-09-08 03:54:35,318 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : DisjointClasses(<http://purl.obolibrary.org/obo/BFO_0000002> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/BFO_0000003>))»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:1429)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:261)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:549)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
2018-09-08 03:54:35,337 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : SubObjectPropertyOf(<http://purl.obolibrary.org/obo/RO_0002333> InverseOf(<http://purl.obolibrary.org/obo/RO_0002215>))»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:743)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:271)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:549)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
2018-09-08 03:54:35,376 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : DisjointClasses(<http://purl.obolibrary.org/obo/BFO_0000003> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/BFO_0000002>))»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:1429)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:261)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:549)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
2018-09-08 03:54:35,389 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : SubClassOf(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002566> <http://purl.obolibrary.org/obo/BFO_0000040>) ObjectUnionOf(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000056> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002418> <http://purl.obolibrary.org/obo/BFO_0000015>)) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000056> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002418> <http://purl.obolibrary.org/obo/BFO_0000015>)))))»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:2101)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:259)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:549)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
robot verify  --catalog catalog-v001.xml -i planp-edit.owl --queries ../sparql/equivalent-classes-violation.sparql ../sparql/trailing-whitespace-violation.sparql ../sparql/owldef-self-reference-violation.sparql ../sparql/xref-syntax-violation.sparql ../sparql/nolabels-violation.sparql -O reports/
PASS Rule ../sparql/equivalent-classes-violation.sparql: 0 violation(s)
PASS Rule ../sparql/trailing-whitespace-violation.sparql: 0 violation(s)
PASS Rule ../sparql/owldef-self-reference-violation.sparql: 0 violation(s)
PASS Rule ../sparql/xref-syntax-violation.sparql: 0 violation(s)
PASS Rule ../sparql/nolabels-violation.sparql: 0 violation(s)
simple_pattern_tester.py ../patterns/ # 2>&1 | tee pattern_schema_checks
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/abnormal.yaml
  warnings.warn("Checking %s" % pattern_doc)
dosdp-tools prototype --obo-prefixes --template=../patterns --outfile=../patterns/pattern.owl
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tools/dosdp-tools/lib/org.slf4j.slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
robot query -f csv -i ../patterns/pattern.owl --query ../sparql/terms.sparql ../patterns/imports/seed.txt
cat ../patterns/imports/seed.txt | sort | uniq > ../patterns/imports/seed_sorted.txt
robot extract -i mirror/ro.owl -T ../patterns/imports/seed_sorted.txt --method BOT -O mirror/ro.owl annotate --ontology-iri http://purl.obolibrary.org/obo/planp/patterns/imports/ro_import.owl -o ../patterns/imports/ro_import.owl
2018-09-08 03:55:04,687 ERROR org.semanticweb.owlapi.model.OWLOntologyID - Ontology IRIs must be absolute; IRI mirror/ro.owl is relative and will be made absolute by prefixing urn:absolute: to it
cat patterns.sh >patterns
chmod a+x patterns
robot  reason -i planp-edit.owl -r ELK relax reduce -r ELK annotate -V http://purl.obolibrary.org/obo/planp/releases/`date +%Y-%m-%d`/planp.owl -o planp.owl
2018-09-08 03:55:15,923 ERROR org.obolibrary.robot.ReasonOperation - Reference violations found: 1302 - reasoning may be incomplete
2018-09-08 03:55:15,926 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000241>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000241>, category=DANGLING]
2018-09-08 03:55:15,927 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubObjectPropertyOf(<http://purl.obolibrary.org/obo/RO_0002584> <http://purl.obolibrary.org/obo/RO_0002328>), referencedObject=<http://purl.obolibrary.org/obo/RO_0002328>, category=DANGLING]
2018-09-08 03:55:15,927 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000184>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000184>, category=DANGLING]
2018-09-08 03:55:15,928 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000525>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000525>, category=DANGLING]
2018-09-08 03:55:15,928 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000155>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000155>, category=DANGLING]
2018-09-08 03:55:15,928 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000597>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000597>, category=DANGLING]
2018-09-08 03:55:15,929 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000267>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000267>, category=DANGLING]
2018-09-08 03:55:15,929 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000839>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000839>, category=DANGLING]
2018-09-08 03:55:15,929 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000750>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000750>, category=DANGLING]
2018-09-08 03:55:15,930 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=Declaration(Class(<http://purl.obolibrary.org/obo/PATO_0000900>)), referencedObject=<http://purl.obolibrary.org/obo/PATO_0000900>, category=DANGLING]
robot convert -i planp.owl -f obo -o planp.obo.tmp && mv planp.obo.tmp planp.obo
ONTOLOGY STORAGE ERROR Could not save ontology to IRI: file:/work/src/ontology/planp.obo.tmp
For details see: http://robot.obolibrary.org/errors#ontology-storage-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
Makefile:50: recipe for target 'planp.obo' failed
make: *** [planp.obo] Error 1
rm imports/ro_terms_combined.txt
mp02gtfh05:ontology smr$
```

**Comment by matentzn** [comment]
Note that most errors are not relevant - these are ROBOT issues that should be suppressed. The real problem is:

```
robot convert -i planp.owl -f obo -o planp.obo.tmp && mv planp.obo.tmp planp.obo
ONTOLOGY STORAGE ERROR Could not save ontology to IRI: file:/work/src/ontology/planp.obo.tmp
For details see: http://robot.obolibrary.org/errors#ontology-storage-error
```

Note to self: make sure the most up to data make file is used.

**Comment by srobb1** [comment]
Can it be something other than one of the common reasons to get the storage error?
 - robot can create the file, robot.obo.tmp is created but is 0 bytes. 
 - I have enough disk space.

**Comment by jamesaoverton** [comment]
Does it work if the file name ends with `obo` instead of `tmp`? You're specifying the `-f` format flag, so using a `tmp` extension should work fine, but ROBOT could have a bug there.

In any case, try adding the `-vvv` option so ROBOT will print the full stack trace.

**Comment by matentzn** [comment]
@srobb1 In order to set you up effectively: Can you share you current setup with me? I send you an email.

**Comment by srobb1** [comment]
@jamesaoverton I tried changing the name, same error. Thanks for the suggestion!

@matentzn My [PLANP ontology is in github](https://github.com/srobb1/planarian-phenotype-ontology). Thank you!

**Comment by matentzn** [comment]
Hey Sofia!

I found what the problem is. It requires a bit of an explanation. The essence is this: 

The current pipeline uses OBO as an intermediate format, which is considerably stricter for Bio-ontologies, and therefore leads to better overall quality. One of the most important restrictions is that annotations should never duplicate: a class can have only one textual definition, one label and one comment (and perhaps some others). Your planp-edit contains a large number of GO classes and re-defines them: This is bad practice and should be avoided at all costs. Example scenario:

```
GO.owl contains: [GO:001 SubClassOf: GO:002] and [GO:001 obo:definition "GO label"] 
planp.owl contains [GO:001 obo:definition "GO label"]
planp.owl imports GO.owl
```

This will cause an error such as (this one is yours):

```
java.io.IOException: errors#ONTOLOGY STORAGE ERROR Could not save ontology to IRI: file:/work/src/ontology/planp.obo.tmp
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:561)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:500)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:246)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:190)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
Caused by: org.semanticweb.owlapi.model.OWLOntologyStorageException: org.obolibrary.oboformat.model.FrameStructureException: multiple def tags not allowed. in frame:Frame(GO:0070727 id( GO:0070727)is_a( GO:0051641)is_a( GO:0033036)def( Any process in which a macromolecule is transported to, and/or maintained in, a specific location at the level of a cell. Localization at the cellular level encompasses movement within the cell, from within the cell to the cell surface, or from one location to another at the surface of a cell.)creation_date( 2009-06-16T04:08:29Z)synonym( cellular macromolecule localisation EXACT)created_by( midori)namespace( biological_process)name( cellular macromolecule localization)def( 
Any process in which a macromolecule is transported to, and/or maintained in, a specific location at the level of a cell. Localization at the cellular level encompasses movement within the cell, from within the cell to the cell surface, or from one location to another at the surface of a cell.
)property_value( IAO:0000412 http://purl.obolibrary.org/obo/go.owl))
	at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:90)
	at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1302)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:559)
	... 6 more
Caused by: org.obolibrary.oboformat.model.FrameStructureException: multiple def tags not allowed. in frame:Frame(GO:0070727 id( GO:0070727)is_a( GO:0051641)is_a( GO:0033036)def( Any process in which a macromolecule is transported to, and/or maintained in, a specific location at the level of a cell. Localization at the cellular level encompasses movement within the cell, from within the cell to the cell surface, or from one location to another at the surface of a cell.)creation_date( 2009-06-16T04:08:29Z)synonym( cellular macromolecule localisation EXACT)created_by( midori)namespace( biological_process)name( cellular macromolecule localization)def( 
Any process in which a macromolecule is transported to, and/or maintained in, a specific location at the level of a cell. Localization at the cellular level encompasses movement within the cell, from within the cell to the cell surface, or from one location to another at the surface of a cell.
)property_value( IAO:0000412 http://purl.obolibrary.org/obo/go.owl))
	at org.obolibrary.oboformat.model.Frame.checkMaxOneCardinality(Frame.java:424)
	at org.obolibrary.oboformat.model.Frame.check(Frame.java:405)
	at org.obolibrary.oboformat.model.OBODoc.check(OBODoc.java:390)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:189)
	at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
	... 11 more
```

Therefore, the way to success is this:
1. Start with a plain empty planp-edit.owl.
2. Add imports you want to use in the Make file in the section labelled IMPORTS = ro

Use DOSDP for generating your definitions (I can help you with that).  I will send you another email now. :)

**Comment by srobb1** [comment]
I corrected that just after I first emailed you. if you pull the changes it
will be fixed. I still get errors.

```
robot convert -i planp.owl -f obo -o planp.obo.tmp && mv planp.obo.tmp
planp.obo
ONTOLOGY STORAGE ERROR Could not save ontology to IRI:
file:/work/src/ontology/planp.obo.tmp
For details see: http://robot.obolibrary.org/errors#ontology-storage-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
Makefile:50: recipe for target 'planp.obo' failed
make: *** [planp.obo] Error 1
```

**Comment by srobb1** [comment]
I corrected that just after I first emailed you. if you pull the changes it
will be fixed. I still get errors.

```
robot convert -i planp.owl -f obo -o planp.obo.tmp && mv planp.obo.tmp
planp.obo
ONTOLOGY STORAGE ERROR Could not save ontology to IRI:
file:/work/src/ontology/planp.obo.tmp
For details see: http://robot.obolibrary.org/errors#ontology-storage-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
Makefile:50: recipe for target 'planp.obo' failed
make: *** [planp.obo] Error 1
```

**Comment by matentzn** [comment]
Closing for now, re-open if necessary

**Comment by matentzn** [comment]
@citmejia do you want to point me to your repository? I can fix it for you. Hopefully.

**Comment by citmejia** [comment]
https://github.com/microbial-conditions-ontology/Microbial-Conditions-Ontology/tree/logicalconsistency/src/ontology

**Comment by matentzn** [comment]
@citmejia How do you run your release? If i do the usual:

cd src/ontology/
make prepare_release

I get some QC violations that let the build fail (self referencing classes). Is this how you do it? Just so I can reproduce the error.

**Comment by citmejia** [comment]
Hello Nico,

I was just doing make.

**Comment by matentzn** [comment]
@citmejia  I hope this fixes it for you:

https://github.com/microbial-conditions-ontology/Microbial-Conditions-Ontology/issues/2

**Comment by citmejia** [comment]
Thank you, Nico. I'm going to check it and I'll let you know.

Le ven. 1 févr. 2019 à 07:06, Nico Matentzoglu <notifications@github.com> a
écrit :
