### ISSUE TITLE
Issue running seed-via-docker.sh on MAC OS 

### ISSUE THREAD

**Issue by tcaden3575** [INCATools/ontology-development-kit#1095]
**I ran  bash ./seed-via-docker.sh on a Mac OS and I am getting the below error:**

**Can you provide any suggestions on getting the docker container to run.**

Status: Downloaded newer image for obolibrary/odkfull:latest
INFO:root:  Copying: /tools/templates/README.md.jinja2 -> target/None/README.md.jinja2
INFO:root:  Copying: /tools/templates/CODE_OF_CONDUCT.md -> target/None/CODE_OF_CONDUCT.md
INFO:root:  Copying: /tools/templates/CONTRIBUTING.md.jinja2 -> target/None/CONTRIBUTING.md.jinja2
INFO:root:  Copying: /tools/templates/.gitignore.jinja2 -> target/None/.gitignore.jinja2
INFO:root:  Copying: /tools/templates/_dynamic_files.jinja2 -> target/None/_dynamic_files.jinja2
INFO:root:  Copying: /tools/templates/issue_template.md.jinja2 -> target/None/issue_template.md.jinja2
INFO:root:Applying templates
INFO:root:  Compiling: /tools/templates/README.md.jinja2 -> target/None/README.md
INFO:root:  Compiling: /tools/templates/CONTRIBUTING.md.jinja2 -> target/None/CONTRIBUTING.md
Traceback (most recent call last):
  File "/tools/odk.py", line 1112, in <module>
    cli()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/tools/odk.py", line 1046, in seed
    s.write(mg.generate(srcf))
  File "/tools/odk.py", line 800, in generate
    return template.render( project = self.context.project, env = {"ODK_VERSION": os.getenv("ODK_VERSION")})
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.10/dist-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'None' has no attribute 'upper'

**Comment by matentzn** [comment]
I just tried these:

Download a test file:

```
wget https://raw.githubusercontent.com/OBOAcademy/obook/master/docs/tutorial/odk_tutorial_2/cato-odk.yaml
```

Update ODK:

```
docker pull obolibrary/odkfull:latest
```

Run test built:

```
curl https://raw.githubusercontent.com/INCATools/ontology-development-kit/master/seed-via-docker.sh | bash -s --  --clean -C cato-odk.yaml
```

And it worked!

Can you try these steps as well and report back?
```

**Comment by gouttegd** [comment]
I do reproduce the exact same error if I tried calling the `seed-via-docker.sh` script _without any argument_, which is probably what the poster has done.

It looks like the `seed` command of the `odk.py` script could be adapted so that it displays a message (maybe the same message as the one shown by `seed --help`) instead of erroring out when it is called without any argument.

**Comment by tcaden3575** [comment]
> Hello @tcaden3575, thank you for reaching out!
> 
> I just tried these:
> 
> Download a test file:
> 
> ```
> wget https://raw.githubusercontent.com/OBOAcademy/obook/master/docs/tutorial/odk_tutorial_2/cato-odk.yaml
> ```
> 
> Update ODK:
> 
> ```
> docker pull obolibrary/odkfull:latest
> ```
> 
> Run test built:
> 
> ```
> curl https://raw.githubusercontent.com/INCATools/ontology-development-kit/master/seed-via-docker.sh | bash -s --  --clean -C cato-odk.yaml
> ```
> 
> And it worked!
> 
> Can you try these steps as well and report back?

I tried the steps and it compiled, but the container came up then disappear. I see this on my terminal:
![image](https://github.com/user-attachments/assets/db88d00b-7ccc-488b-a1f2-c152373ae484)

**Comment by matentzn** [comment]
This looks ok to me; the container only "runs" while the pipeline itself is running, after that it closes!

**Comment by tcaden3575** [comment]
Thanks for your help.
