### ISSUE TITLE
Include script for deploying releases as github files

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#205]
@cmungall will show how this is done for mondo

**Comment by cmungall** [comment]
Makefile:

https://github.com/monarch-initiative/mondo/blob/5b30195d8d4b8058c0cb9233a85c6342cd113090/src/ontology/Makefile#L131-L134

**Comment by cmungall** [comment]
OK @dosumis @matentzn , the github API and the python wrapper makes this easy!

Experiment here: https://github.com/monarch-initiative/mondo/releases/tag/current

We have two options:

 * Keep a single running 'current` release, and delete files and re-upload each time (use `-f` force option)
 * Delete the 'current' release each time and re-create (use `-c` and `-f`)

Either way we lose the download stats, which is a shame but OK, we should do this at the OBO level anyway, cc @kltm

**Comment by cmungall** [comment]
OK, this should be easy

This can be included directly into odk.py
https://github.com/monarch-initiative/mondo/blob/master/src/utils/make-release-assets.py

Then something like this should go in the Makefile template
https://github.com/monarch-initiative/mondo/blob/412aeb1aa564330662793726f110030eb56db5b2/src/ontology/Makefile#L132-L141

Note that there are two targets:

 * one re-created (or creates from scratch) a tag called 'current', and deploys assets there
 * the other creates and deploys to a versioned release

Would be good to have a way to have the user not have to specify the ISO Date

**Comment by cmungall** [comment]
Note the script has

```
    for a in G_rel.get_assets():
        print('Asset: {} Size: {} Downloads: {}'.format(a.name, a.size, a.download_count))
```

we should append this output to a file, so there is a running record of number of downloads of each artefact

**Comment by matentzn** [comment]
The infrastructure for integrating your python based approach can be found [here](https://github.com/INCATools/ontology-development-kit/pull/268). Currently, it fails with:

```
make-release-assets.py --release v2019-08-07 zeco.owl
INFO:root:org=monarch-initiative repo=mondo rel=v2019-08-07
Traceback (most recent call last):
  File "/tools//make-release-assets.py", line 90, in <module>
    make_assets()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tools//make-release-assets.py", line 40, in make_assets
    with open('.token') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.token'
make: *** [Makefile:366: public_release] Error 1
```

I will merge anyways now; just remember this needs developing :P @cmungall

**Comment by cmungall** [comment]
Yes, it assumes your github token is placed into .token

**Comment by gouttegd** [comment]
No longer relevant. The standard Makefile already includes code to create a GitHub release and push the release artefacts to it.
