### ISSUE TITLE
Non purl.obolibrary.org/obo prefixes

### ISSUE THREAD

**Issue by srobb1** [INCATools/ontology-development-kit#243]
Hello,

I am importing EFO. When I create patterns using EFO terms the IRI is in `http://purl.obolibrary.org/obo/EFO_0004038` format and not the correct `http://www.ebi.ac.uk/efo/EFO_0006571` format.

I was told using a `dosdp-tools` argument `--prefixes=myprefixes.yaml` with the prefixes in`myprefixes.yaml` should work (testing now). I manually added this argument to both of the dosdp-tool lines in the Makefile (the one we are not supposed to edit :/ ).

Also, maybe this other issue I have will be fixed once the prefix is corrected, but the EFO terms that I use in my pattern tsv do not get their ancestors imported. (testing now too). Seems like an incorrect IRI might have an effect on this feature :)

Perhaps this `--prefixes` argument could be supplied along with the `--obo-prefixes true` in the project.yaml for the `dosdp_tools_options:` parameter, or maybe it already is possible.

Thanks,
Sofia

**Comment by matentzn** [comment]
@srobb1 did you try add the `--prefixes=myprefixes.yaml` to the `dosdp_tools_options`? Will this allow both standard obo prefixes and the additional ones as specified by the prefixes file?

**Comment by srobb1** [comment]
I tried `dosdp_tools_options: --prefixes=myprefixes.yaml --obo-prefixes=true` in my project.yaml when running `./seed-via-docker.sh`.  It doesn't work when I combine the two, or even when I try only `--prefixes=myprefixes.yaml` without `--obo-prefixes=true`.

I get this error 
```
ERROR:root:b'/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml\n  warnings.warn("Checking %s" % pattern_doc)\n/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml\n  warnings.warn("Checking %s" % pattern_doc)\nException in thread "main" java.io.FileNotFoundException: myprefixes.yaml (No such file or directory)\n\tat java.io.FileInputStream.open0(Native Method)\n\tat java.io.FileInputStream.open(FileInputStream.java:195)\n\tat java.io.FileInputStream.<init>(FileInputStream.java:138)\n\tat java.io.FileReader.<init>(FileReader.java:72)\n\tat org.monarchinitiative.dosdp.cli.Common.$anonfun$prefixes$1(Common.scala:53)\n\tat scala.Option.flatMap(Option.scala:188)\n\tat org.monarchinitiative.dosdp.cli.Common.prefixes(Common.scala:52)\n\tat org.monarchinitiative.dosdp.cli.Common.prefixes$(Common.scala:50)\n\tat org.monarchinitiative.dosdp.cli.Generate$.prefixes(Generate.scala:18)\n\tat org.monarchinitiative.dosdp.cli.Generate$.run(Generate.scala:38)\n\tat org.monarchinitiative.dosdp.cli.Main$.$anonfun$new$1(Main.scala:10)\n\tat org.monarchinitiative.dosdp.cli.Main$.$anonfun$new$1$adapted(Main.scala:10)\n\tat scala.Option.foreach(Option.scala:274)\n\tat org.monarchinitiative.dosdp.cli.Main$.delayedEndpoint$org$monarchinitiative$dosdp$cli$Main$1(Main.scala:10)\n\tat org.monarchinitiative.dosdp.cli.Main$delayedInit$body.apply(Main.scala:6)\n\tat scala.Function0.apply$mcV$sp(Function0.scala:39)\n\tat scala.Function0.apply$mcV$sp$(Function0.scala:39)\n\tat scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)\n\tat scala.App.$anonfun$main$1$adapted(App.scala:80)\n\tat scala.collection.immutable.List.foreach(List.scala:392)\n\tat scala.App.main(App.scala:80)\n\tat scala.App.main$(App.scala:78)\n\tat org.monarchinitiative.dosdp.cli.Main$.main(Main.scala:6)\n\tat org.monarchinitiative.dosdp.cli.Main.main(Main.scala)\nmake: *** [Makefile:340: ../patterns/data/default/abnormalAnatomicalEntity.ofn] Error 1\n'
Traceback (most recent call last):
  File "/tools/odk.py", line 687, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
id: simr
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tools/odk.py", line 652, in seed
    runcmd("cd {}/src/ontology && make && git commit -m 'initial commit' -a && make prepare_initial_release && git commit -m 'first release'".format(outdir))
  File "/tools/odk.py", line 681, in runcmd
    raise Exception('Failed: {}'.format(cmd))
Exception: Failed: cd target/simr/src/ontology && make && git commit -m 'initial commit' -a && make prepare_initial_release && git commit -m 'first release'
```
I noticed the `java.io.FileNotFoundException: myprefixes.yaml`. I moved my file into the correct directory in the target directory, and ran again. With just the prefixes= option, it works, but i get this error when i combine the two arguments

`dosdp_tools_options: --obo-prefixes=true --prefixes=myprefixes.yaml`

```
ERROR:root:b'/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml\n  warnings.warn("Checking %s" % pattern_doc)\n'
Traceback (most recent call last):
  File "/tools/odk.py", line 687, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tools/odk.py", line 652, in seed
    runcmd("cd {}/src/ontology && make && git commit -m 'initial commit' -a && make prepare_initial_release && git commit -m 'first release'".format(outdir))
  File "/tools/odk.py", line 681, in runcmd
    raise Exception('Failed: {}'.format(cmd))
Exception: Failed: cd target/simr/src/ontology && make && git commit -m 'initial commit' -a && make prepare_initial_release && git commit -m 'first release'
```

**Comment by balhoff** [comment]
I think this error is not in dosdp-tools but in the python schema checker.

**Comment by matentzn** [comment]
There is not enough to go on here with this error message. The first thing is of course correct: if you use the prefix file parameter, you need the file to be present. @matentzn make sure that this is dealt with at some point.

@srobb1 can you email me the whole log of the error message please?

**Comment by matentzn** [comment]
Please re-open if still a problem.
