### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'env' is undefined

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#312]
This line in the Makefile is causing issues

```
ODK_VERSION =               {{ env['ODK_VERSION'] or "Unknown" }}
```

```
INFO:root:  Compiling: ./template/src/ontology/Makefile.jinja2 -> target/myont//src/ontology/Makefile
Traceback (most recent call last):
  File "./odk/odk.py", line 770, in <module>
    cli()
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./odk/odk.py", line 718, in seed
    s.write(mg.generate(srcf))
  File "./odk/odk.py", line 494, in generate
    return template.render( project = self.context.project)
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 14, in top-level template code
  File "/Users/cjm/repos/ontology-development-kit/venv/lib/python3.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'env' is undefined

```

**Comment by matentzn** [comment]
Hmmm I guess it’s causing issues because you are not using docker?

**Comment by matentzn** [comment]
I will see what I can do!

**Comment by matentzn** [comment]
Should be fixed now: https://github.com/INCATools/ontology-development-kit/blob/0dd8ddbc48281535c31de379d187881e36c59609/template/src/ontology/Makefile.jinja2#L14
