### ISSUE TITLE
barfing on example

### ISSUE THREAD

**Issue by mateolan** [INCATools/ontology-development-kit#34]
I was trying to set-up a new ontology and got errors pulling-in import ontologies.  It looks like OSK pulls in ontologies as '.txt' files but then searches for .owl files to import and barfs on not finding them.
What am I missing?
Relevant snips from command and error message below:

campus-108-115:ontology-starter-kit matthewlange$ ./seed-my-ontology-repo.pl -d po -d ro -d pato -d mmo -u mateolan -t "Food Phenotype Ontology" -c foodphen
**<errorSnip>**
WRITING: target/food-phenotype-ontology/src/ontology/imports/po_terms.txt
WRITING: target/food-phenotype-ontology/src/ontology/imports/ro_terms.txt
WRITING: target/food-phenotype-ontology/src/ontology/imports/pato_terms.txt
WRITING: target/food-phenotype-ontology/src/ontology/imports/mmo_terms.txt
WRITING: target/food-phenotype-ontology/src/ontology/reports/README.md
**</errorSnip>
<errorSnip>**
EXECUTING: git init
Initialized empty Git repository in /Users/matthewlange/ontology-starter-kit/target/food-phenotype-ontology/.git/
EXECUTING: git add -A .
EXECUTING: git commit -m 'initial commit of ontology sources of foodphen using ontology-starter-kit' -a
[master (root-commit) 58f0349] initial commit of ontology sources of foodphen using ontology-starter-kit
 34 files changed, 735 insertions(+)
 create mode 100644 src/ontology/foodphen-edit.owl
 create mode 100644 src/ontology/foodphen-idranges.owl
 create mode 100644 src/ontology/imports/mmo_terms.txt
 create mode 100644 src/ontology/imports/pato_terms.txt
 create mode 100644 src/ontology/imports/po_terms.txt
 create mode 100644 src/ontology/imports/ro_terms.txt
**</errorSnip>
<errorSnip>**
Preparing initial release, may take a few minutes, or longer if you depend on large ontologies like chebi
EXECUTING: cd src/ontology && make prepare_release && echo SUCCESS || echo FAILURE
robot verify -i foodphen-edit.owl --queries ../sparql/equivalent-classes-violation.sparql ../sparql/trailing-whitespace-violation.sparql ../sparql/owldef-self-reference-violation.sparql ../sparql/xref-syntax-violation.sparql ../sparql/nolabels-violation.sparql -O reports/
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/foodphen/imports/po_import.owl> Cause: /Users/matthewlange/ontology-starter-kit/target/food-phenotype-ontology/src/ontology/imports/po_import.owl (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1690)
**</errorSnip>
<errorSnip>**
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: /Users/matthewlange/ontology-starter-kit/target/food-phenotype-ontology/src/ontology/imports/po_import.owl (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:207)
**</errorSnip>
<errorSnip>**
Caused by: java.io.FileNotFoundException: /Users/matthewlange/ontology-starter-kit/target/food-phenotype-ontology/src/ontology/imports/po_import.owl (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
**</errorSnip>
<errDirListing>**
matthewlange$ ls /Users/matthewlange/ontology-starter-kit/target/food-phenotype-ontology/src/ontology/imports
mmo_terms.txt	pato_terms.txt	po_terms.txt	ro_terms.txt
**</errDirListing>**

**Comment by matentzn** [comment]
Hey, closing this issue due to long inactivity. Please re-open if necessary.
