### ISSUE TITLE
OSK barfing on ontology imports

### ISSUE THREAD

**Issue by clairececchini** [INCATools/ontology-development-kit#40]
See snippet of error below. INCA_Tools barfs on inclusion of BFO, same happens on PATO, RO, etc.

What to do?

<error snip>
EXECUTING: cd src/ontology && make prepare_release && echo SUCCESS || echo FAILURE
robot verify -i pahf-edit.owl --queries ../sparql/equivalent-classes-violation.sparql ../sparql/trailing-whitespace-violation.sparql ../sparql/owldef-self-reference-violation.sparql ../sparql/xref-syntax-violation.sparql ../sparql/nolabels-violation.sparql -O reports/
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/pahf/imports/ro_import.owl> Cause: /Users/matthewlange/ontology-starter-kit/target/physical-activity-health-and-fitness-ontology/src/ontology/imports/ro_import.owl (No such file or directory)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1690)
at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.Ontology(OWLFunctionalSyntaxParser.java:231)
at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.parse(OWLFunctionalSyntaxParser.java:171)
at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxOWLParser.parse(OWLFunctionalSyntaxOWLParser.java:77)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:197)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1098)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1054)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1004)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1015)
at org.obolibrary.robot.IOHelper.loadOntology(IOHelper.java:305)
at org.obolibrary.robot.IOHelper.loadOntology(IOHelper.java:189)
at org.obolibrary.robot.CommandLineHelper.getInputOntology(CommandLineHelper.java:295)
at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:354)
at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:319)
at org.obolibrary.robot.VerifyCommand.execute(VerifyCommand.java:132)
at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:58)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: /Users/matthewlange/ontology-starter-kit/target/physical-activity-health-and-fitness-ontology/src/ontology/imports/ro_import.owl (No such file or directory)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:207)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1098)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1054)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:957)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1648)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1684)
... 18 more
Caused by: java.io.FileNotFoundException: /Users/matthewlange/ontology-starter-kit/target/physical-activity-health-and-fitness-ontology/src/ontology/imports/ro_import.owl (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:165)
at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:127)
at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:232)
at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:197)
... 23 more
java.lang.IllegalArgumentException: A valid input ontology must be specified
at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:358)
at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:319)
at org.obolibrary.robot.VerifyCommand.execute(VerifyCommand.java:132)
at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:58)
usage: robot [command] [options] <arguments>
 -h,--help                  print usage information
 -noprefixes                do not use default prefixes
 -p,--prefix <arg>          add a prefix 'foo: http://bar'
 -P,--prefixes <arg>        use prefixes from JSON-LD file
 -V,--version               print version information
 -v,--verbose               increased logging
 -vv,--very-verbose         high logging
 -vvv,--very-very-verbose   maximum logging
 -x,--xml-entities          use entity substitution with ontology XML
                            output
commands:
 help             print help for command
 annotate         annotate ontology
 convert          convert ontology
 diff             find the differences between two ontologies
 export-prefixes  export prefixes to a file
 extract          extract terms from an ontology
 filter           filter ontology axioms
 materialize      materialize ontology
 merge            merge ontologies
 mirror           mirror ontology imports closure
 query            query an ontology
 reason           reason ontology
 reduce           reduce ontology
 relax            relax ontology
 repair           repair terms from an ontology
 report           report terms from an ontology
 template         build an ontology from a template
 unmerge          unmerge ontologies
 validate-profile validate ontology against an OWL profile
 verify           Runs a sparql query on an ontology. Any results of the query are violations, counted, and reported
make: *** [sparql_test] Error 1
FAILURE
EXECUTING: git add src/ontology/imports/*{obo,owl}
fatal: pathspec 'src/ontology/imports/*obo' did not match any files
ERROR RUNNING: git add src/ontology/imports/*{obo,owl}
Exiting. Run with '-f' to force execution and ignore errors at ./seed-my-ontology-repo.pl line 205.
</error snip>

**Comment by cmungall** [comment]
can you add the exact command you ran?

Also is this on an up to date version? Looks similar to a problem we had a while ago

**Comment by clairececchini** [comment]
@cmungall what's the recommended way to update the version? since I created my ontology-repo with the starter-kit and not with a fork I am not sure how to include any upstream changes from after I created my ontology-repo.

For reference, here's my ontology-repo: github.com/IC-FOODS/physical-activity-health-fitness

**Comment by cmungall** [comment]
OK my initial guess was wrong. I think there is something wrong with your local setup. Unfortunately I can't help much here

It's complaining: `/Users/matthewlange/ontology-starter-kit/target/physical-activity-health-and-fitness-ontology/src/ontology/imports/ro_import.owl (No such file or directory) `

but this is there:

https://github.com/IC-FOODS/physical-activity-health-fitness/blob/master/src/ontology/imports/ro_import.owl

**Comment by cmungall** [comment]
Can you should the command you are running?

Are you in an already generated repository, or are you trying to make a new one from scratch?

**Comment by adhollander** [comment]
Possibly related to this error, @mateolan and I were trying to create a new repository and ran into similar errors:

> cp: cannot stat `imports/*{owl,obo}': No such file or directory

After running  
` cp -R src/ontology/imports/ imports`

 we were able to execute lines 147 to 160 in seed-my-ontology-repo.pl. 
Should that copying action happen from within the script? Please take a look at https://github.com/adhollander/extension-expertise-ontology and see if it looks normal.

This was done on an ancient Ubuntu (Xubuntu 12.04), with Perl 5 version 14 and Java 1.8.0. Is there a piece that I'm missing?

**Comment by mateolan** [comment]
Note that the command executed by adhollander was 
`./seed-my-ontology-repo.pl  -d bfo  envo -u adhollander -t "Extension Expertise Ontologies" eexp
`
This worked fine on my mac OSX running Perl  (v5.18.2), Java version "1.8.0_171"

Happy to help define/document set-up requirements... but at a loss about why this is occurring.

**Comment by matentzn** [comment]
I will close his for now. Note however that the BFO import still does not work, but for a different reason. will create another ticket
