### ISSUE TITLE
java.lang.NullPointerException when generating derived ontology files

### ISSUE THREAD

**Issue by dillerm** [INCATools/ontology-development-kit#491]
I'm getting this error when trying to prepare a release according to the ODK Release Manager Notes.

Here is what my command line looks like:

`sh run.sh make all`

Here is the ROBOT command that the script seems to break on:

```
if [ true  = true ]; then robot -vvv --catalog catalog-v001.xml query -i mirror/omrse.owl --update ../sparql/preprocess-module.ru \
	extract -T imports/omrse_terms_combined.txt --force true --copy-ontology-annotations true --individuals include --method BOT \
	query --update ../sparql/inject-subset-declaration.ru --update ../sparql/postprocess-module.ru \
	annotate --ontology-iri http://purl.obolibrary.org/obo/orcs/imports/omrse_import.owl annotate -V http://purl.obolibrary.org/obo/orcs/releases/2021-10-29/imports/omrse_import.owl --annotation owl:versionInfo 2021-10-29 --output imports/omrse_import.owl.tmp.owl && mv imports/omrse_import.owl.tmp.owl imports/omrse_import.owl; fi
```

Here is the error message, along with some of the last few lines of the verbose output:

```
2021-10-29 19:17:19,740 DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.TripleLogger - Loaded OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/orcs.owl>) VersionIRI(<http://purl.obolibrary.org/obo/orcs/releases/2021-10-05/orcs.owl>))
2021-10-29 19:17:19,871 DEBUG org.obolibrary.robot.IOHelper - Saving ontology as OBO Format with to IRI file:/work/src/ontology/orcs.obo.tmp.obo
2021-10-29 19:17:20,593 DEBUG org.obolibrary.robot.ExceptionHelper - {} missing exception message.
java.lang.NullPointerException
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:619)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:171)
	at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1700)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:838)
	at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:671)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
null
java.lang.NullPointerException
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:619)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:171)
	at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1700)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:838)
	at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:671)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
make: *** [Makefile:430: orcs.obo] Error 1
rm imports/omrse_terms_combined.txt
```

Lastly, here is the link to the repository: https://github.com/ufbmi/ORCS

**Comment by matentzn** [comment]
Hmm, I will have to see the whole ontology. The actually error happens in the step that transform orcs.owl to orcs.obo. Debugging this is can be very difficult. Do you want to share orcs.owl with me (you can generate it by running sh run.sh make orcs.owl). Also where did you get the "make all" information? The docs should say "prepare_release", not "all".

**Comment by matentzn** [comment]
@dillerm I am assuming this has been sorted! :) Closing
